name: First workflowV1
on: push
jobs:
    build-job:
        runs-on: ubuntu-latest
        steps:
            - name: Build the application
              run: |
                  sleep 3 
                  echo "Building the app"  > app.txt
    test-job:
        runs-on: ubuntu-latest
        steps:
            - name: Test the app
              run: |
                  sleep 3
                  cat app.txt
                  echo "Testing the app"  >> app.txt
    deploy-job:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy the app
              run: |
                  sleep 1
                  cat app.txt
                  echo "Deploying the app"  >> app.txt
              
              
            
